# Ignore maximize requests from apps.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Zen Browser Picture-in-Picture rules
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = size 800 450, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
